//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Kontakt os</summary>
	[PublishedContentModel("kontaktOs")]
	public partial class KontaktOs : PublishedContentModel, IBannerImg
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "kontaktOs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public KontaktOs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<KontaktOs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("banner")]
		public IPublishedContent Banner
		{
			get { return Umbraco.Web.PublishedContentModels.BannerImg.GetBanner(this); }
		}

		///<summary>
		/// bannerHead
		///</summary>
		[ImplementPropertyType("bannerHead")]
		public string BannerHead
		{
			get { return Umbraco.Web.PublishedContentModels.BannerImg.GetBannerHead(this); }
		}
	}
}
