//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Nyhed</summary>
	[PublishedContentModel("nyhed")]
	public partial class Nyhed : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "nyhed";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Nyhed(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Nyhed, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// nBody
		///</summary>
		[ImplementPropertyType("nBody")]
		public string NBody
		{
			get { return this.GetPropertyValue<string>("nBody"); }
		}

		///<summary>
		/// nHead
		///</summary>
		[ImplementPropertyType("nHead")]
		public string NHead
		{
			get { return this.GetPropertyValue<string>("nHead"); }
		}

		///<summary>
		/// nImg
		///</summary>
		[ImplementPropertyType("nImg")]
		public IPublishedContent NImg
		{
			get { return this.GetPropertyValue<IPublishedContent>("nImg"); }
		}
	}
}
